# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('logo', models.URLField()),
                ('video_banner', models.URLField()),
                ('profile_banner', models.URLField()),
                ('url', models.URLField()),
                ('views', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('created_at', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=120)),
                ('language', models.CharField(max_length=120)),
                ('broadcaster_language', models.CharField(max_length=120)),
                ('mature', models.BooleanField(default=False)),
                ('partner', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('draft', models.BooleanField(default=False)),
                ('publish', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
